### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/BMP085_Breakout#1]
The Wire.requestFrom() returns after the I2C transaction has completely finished and the received data is stored in the receive buffer in the Wire library. There is no need to wait for something after Wire.requestFrom().

When there was a I2C bus error or I2C collision, the Wire.requestFrom() will probably return with no received data. In that case, the while-loop will halt the sketch.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I was browsing some issues when I noticed this issue that was filed. When the code was originally written, I don't believe that we were aware of the [common mistakes that came with using the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1).

I have [removed the lines](https://github.com/sparkfun/BMP085_Breakout/commit/e64cc4762080cd6fa09a442011cb55ce5e14d4e6).
